-- begin ECO_ADDRESS
alter table ECO_ADDRESS add constraint FK_ECO_ADDRESS_ON_COORDINATES foreign key (COORDINATES_ID) references ECO_POINT(ID)^
alter table ECO_ADDRESS add constraint FK_ECO_ADDRESS_ON_STREET foreign key (STREET_ID) references ECO_STREET(ID)^
create unique index IDX_ECO_ADDRESS_UNIQ_COORDINATES_ID on ECO_ADDRESS (COORDINATES_ID) ^
create unique index IDX_ECO_ADDRESS_UNIQ_STREET_NUMBER on ECO_ADDRESS (STREET_NUMBER) ^
create index IDX_ECO_ADDRESS_ON_COORDINATES on ECO_ADDRESS (COORDINATES_ID)^
create index IDX_ECO_ADDRESS_ON_STREET on ECO_ADDRESS (STREET_ID)^
-- end ECO_ADDRESS
-- begin ECO_ORGANIZATION
create unique index IDX_ECO_ORGANIZATION_UNIQ_INN on ECO_ORGANIZATION (INN) ^
-- end ECO_ORGANIZATION
-- begin ECO_STREET
create unique index IDX_ECO_STREET_UNIQ_NAME on ECO_STREET (NAME) ^
-- end ECO_STREET
-- begin ECO_BUILDING
alter table ECO_BUILDING add constraint FK_ECO_BUILDING_ON_ADDRESS foreign key (ADDRESS_ID) references ECO_ADDRESS(ID)^
create unique index IDX_ECO_BUILDING_UNIQ_ADDRESS_ID on ECO_BUILDING (ADDRESS_ID) ^
create index IDX_ECO_BUILDING_ON_ADDRESS on ECO_BUILDING (ADDRESS_ID)^
-- end ECO_BUILDING

-- begin ECO_BUILDING_ORGANIZATION_LINK
alter table ECO_BUILDING_ORGANIZATION_LINK add constraint FK_BUIORG_ON_BUILDING foreign key (BUILDING_ID) references ECO_BUILDING(ID)^
alter table ECO_BUILDING_ORGANIZATION_LINK add constraint FK_BUIORG_ON_ORGANIZATION foreign key (ORGANIZATION_ID) references ECO_ORGANIZATION(ID)^
-- end ECO_BUILDING_ORGANIZATION_LINK
