-- begin ECO_ADDRESS
alter table ECO_ADDRESS add constraint FK_ECO_ADDRESS_ON_COORDINATES foreign key (COORDINATES_ID) references ECO_POINT(ID)^
alter table ECO_ADDRESS add constraint FK_ECO_ADDRESS_ON_STREET foreign key (STREET_ID) references ECO_STREET(ID)^
create unique index IDX_ECO_ADDRESS_UK_COORDINATES_ID on ECO_ADDRESS (COORDINATES_ID) where DELETE_TS is null ^
create index IDX_ECO_ADDRESS_ON_COORDINATES on ECO_ADDRESS (COORDINATES_ID)^
create index IDX_ECO_ADDRESS_ON_STREET on ECO_ADDRESS (STREET_ID)^
-- end ECO_ADDRESS
-- begin ECO_BUILDING
alter table ECO_BUILDING add constraint FK_ECO_BUILDING_ON_ADDRESS foreign key (ADDRESS_ID) references ECO_ADDRESS(ID)^
create unique index IDX_ECO_BUILDING_UK_ADDRESS_ID on ECO_BUILDING (ADDRESS_ID) where DELETE_TS is null ^
create index IDX_ECO_BUILDING_ON_ADDRESS on ECO_BUILDING (ADDRESS_ID)^
-- end ECO_BUILDING
-- begin ECO_BUILDING_ORGANIZATION_LINK
alter table ECO_BUILDING_ORGANIZATION_LINK add constraint FK_BUIORG_ON_BUILDING foreign key (BUILDING_ID) references ECO_BUILDING(ID)^
alter table ECO_BUILDING_ORGANIZATION_LINK add constraint FK_BUIORG_ON_ORGANIZATION foreign key (ORGANIZATION_ID) references ECO_ORGANIZATION(ID)^
-- end ECO_BUILDING_ORGANIZATION_LINK
