alter table ECO_ORGANIZATION add constraint FK_ECO_ORGANIZATION_ON_IMAGE_FILE foreign key (IMAGE_FILE_ID) references SYS_FILE(ID);
create index IDX_ECO_ORGANIZATION_ON_IMAGE_FILE on ECO_ORGANIZATION (IMAGE_FILE_ID);
